language: node_js

install:
- cd extension; npm install; cd ..
- cd frontend; npm install; cd ..

env: # important! Without the top-level env, no job will be allowed to fail.
  - JOB_DEFAULT=test

matrix:
  fast_finish: true
  include:
    - node_js: 8
      env: TYPE=UNIT_CODESTYLE_DEPENDENCY
      script:
      - cd extension
      - npm run test:unit
      - npm run lint
      - npm run check
      - cd ../..
      - cd frontend
      - npm run test
      - npm run lint
      - npm run check
    - node_js: 8
      env: TYPE=INTEGRATION
      script:
      - if [[ "$INTEGRATION_CREDENTIALS" ]]; then echo "${INTEGRATION_CREDENTIALS}" > .integration-credentials.js; fi
      - cd extension
      - if [[ "$INTEGRATION_CREDENTIALS" ]]; then npm run test:integration; fi
  allow_failures:
    - node_js: 8
      env: TYPE=INTEGRATION

notifications:
  slack:
    rooms:
      secure: 
    on_success: change
    on_failure: always
